# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 628)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.Plate_Controller_Fr = QtWidgets.QFrame(self.centralWidget)
        self.Plate_Controller_Fr.setGeometry(QtCore.QRect(10, 10, 311, 211))
        self.Plate_Controller_Fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Plate_Controller_Fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Plate_Controller_Fr.setObjectName("Plate_Controller_Fr")
        self.Plate_Controller_La = QtWidgets.QLabel(self.Plate_Controller_Fr)
        self.Plate_Controller_La.setGeometry(QtCore.QRect(10, 0, 101, 21))
        self.Plate_Controller_La.setObjectName("Plate_Controller_La")
        self.Plate_Controller_Apply_Bu = QtWidgets.QPushButton(self.Plate_Controller_Fr)
        self.Plate_Controller_Apply_Bu.setGeometry(QtCore.QRect(22, 170, 271, 32))
        self.Plate_Controller_Apply_Bu.setObjectName("Plate_Controller_Apply_Bu")
        self.Plate_Controller_PID_GB = QtWidgets.QGroupBox(self.Plate_Controller_Fr)
        self.Plate_Controller_PID_GB.setGeometry(QtCore.QRect(20, 40, 121, 131))
        self.Plate_Controller_PID_GB.setObjectName("Plate_Controller_PID_GB")
        self.PID_Kd_Box = QtWidgets.QDoubleSpinBox(self.Plate_Controller_PID_GB)
        self.PID_Kd_Box.setGeometry(QtCore.QRect(30, 90, 81, 24))
        self.PID_Kd_Box.setDecimals(4)
        self.PID_Kd_Box.setMinimum(-999.99)
        self.PID_Kd_Box.setMaximum(999.99)
        self.PID_Kd_Box.setSingleStep(0.1)
        self.PID_Kd_Box.setObjectName("PID_Kd_Box")
        self.PID_Kp_La = QtWidgets.QLabel(self.Plate_Controller_PID_GB)
        self.PID_Kp_La.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.PID_Kp_La.setLineWidth(2)
        self.PID_Kp_La.setObjectName("PID_Kp_La")
        self.PID_Kd_La = QtWidgets.QLabel(self.Plate_Controller_PID_GB)
        self.PID_Kd_La.setGeometry(QtCore.QRect(10, 90, 21, 16))
        self.PID_Kd_La.setLineWidth(2)
        self.PID_Kd_La.setObjectName("PID_Kd_La")
        self.PID_Ki_Box = QtWidgets.QDoubleSpinBox(self.Plate_Controller_PID_GB)
        self.PID_Ki_Box.setGeometry(QtCore.QRect(30, 60, 81, 24))
        self.PID_Ki_Box.setDecimals(4)
        self.PID_Ki_Box.setMinimum(-999.99)
        self.PID_Ki_Box.setMaximum(999.99)
        self.PID_Ki_Box.setSingleStep(0.1)
        self.PID_Ki_Box.setObjectName("PID_Ki_Box")
        self.PID_Kp_Box = QtWidgets.QDoubleSpinBox(self.Plate_Controller_PID_GB)
        self.PID_Kp_Box.setGeometry(QtCore.QRect(30, 30, 81, 24))
        self.PID_Kp_Box.setDecimals(4)
        self.PID_Kp_Box.setMinimum(-999.99)
        self.PID_Kp_Box.setMaximum(999.99)
        self.PID_Kp_Box.setSingleStep(0.1)
        self.PID_Kp_Box.setObjectName("PID_Kp_Box")
        self.PID_Ki_La = QtWidgets.QLabel(self.Plate_Controller_PID_GB)
        self.PID_Ki_La.setGeometry(QtCore.QRect(10, 60, 21, 16))
        self.PID_Ki_La.setLineWidth(2)
        self.PID_Ki_La.setObjectName("PID_Ki_La")
        self.Plate_Controller_SMC_GB = QtWidgets.QGroupBox(self.Plate_Controller_Fr)
        self.Plate_Controller_SMC_GB.setGeometry(QtCore.QRect(170, 40, 121, 101))
        self.Plate_Controller_SMC_GB.setObjectName("Plate_Controller_SMC_GB")
        self.SMC_k1_Box = QtWidgets.QDoubleSpinBox(self.Plate_Controller_SMC_GB)
        self.SMC_k1_Box.setGeometry(QtCore.QRect(30, 60, 81, 24))
        self.SMC_k1_Box.setDecimals(4)
        self.SMC_k1_Box.setMinimum(-999.99)
        self.SMC_k1_Box.setMaximum(999.99)
        self.SMC_k1_Box.setSingleStep(0.1)
        self.SMC_k1_Box.setObjectName("SMC_k1_Box")
        self.SMC_K_Box = QtWidgets.QDoubleSpinBox(self.Plate_Controller_SMC_GB)
        self.SMC_K_Box.setGeometry(QtCore.QRect(30, 30, 81, 24))
        self.SMC_K_Box.setDecimals(4)
        self.SMC_K_Box.setMinimum(-999.99)
        self.SMC_K_Box.setMaximum(999.99)
        self.SMC_K_Box.setSingleStep(0.1)
        self.SMC_K_Box.setObjectName("SMC_K_Box")
        self.SMC_k1_La = QtWidgets.QLabel(self.Plate_Controller_SMC_GB)
        self.SMC_k1_La.setGeometry(QtCore.QRect(10, 60, 21, 16))
        self.SMC_k1_La.setLineWidth(2)
        self.SMC_k1_La.setObjectName("SMC_k1_La")
        self.SMC_K_La = QtWidgets.QLabel(self.Plate_Controller_SMC_GB)
        self.SMC_K_La.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.SMC_K_La.setLineWidth(2)
        self.SMC_K_La.setObjectName("SMC_K_La")
        self.Plate_Controller_PID_Ch = QtWidgets.QRadioButton(self.Plate_Controller_Fr)
        self.Plate_Controller_PID_Ch.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.Plate_Controller_PID_Ch.setObjectName("Plate_Controller_PID_Ch")
        self.Plate_Controller_SMC_Ch = QtWidgets.QRadioButton(self.Plate_Controller_Fr)
        self.Plate_Controller_SMC_Ch.setGeometry(QtCore.QRect(170, 20, 51, 20))
        self.Plate_Controller_SMC_Ch.setObjectName("Plate_Controller_SMC_Ch")
        self.Mode_Fr = QtWidgets.QFrame(self.centralWidget)
        self.Mode_Fr.setGeometry(QtCore.QRect(9, 240, 311, 381))
        self.Mode_Fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mode_Fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mode_Fr.setObjectName("Mode_Fr")
        self.Mode_La = QtWidgets.QLabel(self.Mode_Fr)
        self.Mode_La.setGeometry(QtCore.QRect(10, 0, 101, 21))
        self.Mode_La.setObjectName("Mode_La")
        self.Mode_Circle_GB = QtWidgets.QGroupBox(self.Mode_Fr)
        self.Mode_Circle_GB.setGeometry(QtCore.QRect(10, 40, 291, 91))
        self.Mode_Circle_GB.setObjectName("Mode_Circle_GB")
        self.Circle_R_La = QtWidgets.QLabel(self.Mode_Circle_GB)
        self.Circle_R_La.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.Circle_R_La.setLineWidth(2)
        self.Circle_R_La.setObjectName("Circle_R_La")
        self.Circle_CentralY_La = QtWidgets.QLabel(self.Mode_Circle_GB)
        self.Circle_CentralY_La.setGeometry(QtCore.QRect(190, 30, 61, 16))
        self.Circle_CentralY_La.setLineWidth(2)
        self.Circle_CentralY_La.setObjectName("Circle_CentralY_La")
        self.Circle_CentralX_La = QtWidgets.QLabel(self.Mode_Circle_GB)
        self.Circle_CentralX_La.setGeometry(QtCore.QRect(100, 30, 61, 16))
        self.Circle_CentralX_La.setLineWidth(2)
        self.Circle_CentralX_La.setObjectName("Circle_CentralX_La")
        self.Circle_R_Box = QtWidgets.QSpinBox(self.Mode_Circle_GB)
        self.Circle_R_Box.setGeometry(QtCore.QRect(10, 50, 81, 24))
        self.Circle_R_Box.setMaximum(120)
        self.Circle_R_Box.setObjectName("Circle_R_Box")
        self.Circle_CentralX_Box = QtWidgets.QSpinBox(self.Mode_Circle_GB)
        self.Circle_CentralX_Box.setGeometry(QtCore.QRect(100, 50, 81, 24))
        self.Circle_CentralX_Box.setMaximum(320)
        self.Circle_CentralX_Box.setObjectName("Circle_CentralX_Box")
        self.Circle_CentralY_Box = QtWidgets.QSpinBox(self.Mode_Circle_GB)
        self.Circle_CentralY_Box.setGeometry(QtCore.QRect(190, 50, 81, 24))
        self.Circle_CentralY_Box.setMaximum(320)
        self.Circle_CentralY_Box.setObjectName("Circle_CentralY_Box")
        self.Mode_Rectangle_RB = QtWidgets.QGroupBox(self.Mode_Fr)
        self.Mode_Rectangle_RB.setGeometry(QtCore.QRect(10, 130, 291, 141))
        self.Mode_Rectangle_RB.setObjectName("Mode_Rectangle_RB")
        self.Rectangle_TopLeftX_La = QtWidgets.QLabel(self.Mode_Rectangle_RB)
        self.Rectangle_TopLeftX_La.setGeometry(QtCore.QRect(40, 30, 81, 16))
        self.Rectangle_TopLeftX_La.setLineWidth(2)
        self.Rectangle_TopLeftX_La.setObjectName("Rectangle_TopLeftX_La")
        self.Rectangle_BotRightX_La = QtWidgets.QLabel(self.Mode_Rectangle_RB)
        self.Rectangle_BotRightX_La.setGeometry(QtCore.QRect(170, 30, 101, 16))
        self.Rectangle_BotRightX_La.setLineWidth(2)
        self.Rectangle_BotRightX_La.setObjectName("Rectangle_BotRightX_La")
        self.Rectangle_TopLeftY_La = QtWidgets.QLabel(self.Mode_Rectangle_RB)
        self.Rectangle_TopLeftY_La.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.Rectangle_TopLeftY_La.setLineWidth(2)
        self.Rectangle_TopLeftY_La.setObjectName("Rectangle_TopLeftY_La")
        self.Rectangle_BotRightY_La = QtWidgets.QLabel(self.Mode_Rectangle_RB)
        self.Rectangle_BotRightY_La.setGeometry(QtCore.QRect(170, 80, 101, 16))
        self.Rectangle_BotRightY_La.setLineWidth(2)
        self.Rectangle_BotRightY_La.setObjectName("Rectangle_BotRightY_La")
        self.Rectangle_TopLeftX_Box = QtWidgets.QSpinBox(self.Mode_Rectangle_RB)
        self.Rectangle_TopLeftX_Box.setGeometry(QtCore.QRect(40, 50, 81, 24))
        self.Rectangle_TopLeftX_Box.setMaximum(320)
        self.Rectangle_TopLeftX_Box.setObjectName("Rectangle_TopLeftX_Box")
        self.Rectangle_TopLeftY_Box = QtWidgets.QSpinBox(self.Mode_Rectangle_RB)
        self.Rectangle_TopLeftY_Box.setGeometry(QtCore.QRect(40, 100, 81, 24))
        self.Rectangle_TopLeftY_Box.setMaximum(320)
        self.Rectangle_TopLeftY_Box.setObjectName("Rectangle_TopLeftY_Box")
        self.Rectangle_BotRightX_Box = QtWidgets.QSpinBox(self.Mode_Rectangle_RB)
        self.Rectangle_BotRightX_Box.setGeometry(QtCore.QRect(170, 50, 81, 24))
        self.Rectangle_BotRightX_Box.setMaximum(320)
        self.Rectangle_BotRightX_Box.setObjectName("Rectangle_BotRightX_Box")
        self.Rectangle_BotRightY_Box = QtWidgets.QSpinBox(self.Mode_Rectangle_RB)
        self.Rectangle_BotRightY_Box.setGeometry(QtCore.QRect(170, 100, 81, 24))
        self.Rectangle_BotRightY_Box.setMaximum(320)
        self.Rectangle_BotRightY_Box.setObjectName("Rectangle_BotRightY_Box")
        self.Mode_FreeSet_GB = QtWidgets.QGroupBox(self.Mode_Fr)
        self.Mode_FreeSet_GB.setGeometry(QtCore.QRect(10, 270, 291, 71))
        self.Mode_FreeSet_GB.setObjectName("Mode_FreeSet_GB")
        self.FreeSet_X_La = QtWidgets.QLabel(self.Mode_FreeSet_GB)
        self.FreeSet_X_La.setGeometry(QtCore.QRect(20, 30, 21, 16))
        self.FreeSet_X_La.setLineWidth(2)
        self.FreeSet_X_La.setObjectName("FreeSet_X_La")
        self.FreeSet_Y_La = QtWidgets.QLabel(self.Mode_FreeSet_GB)
        self.FreeSet_Y_La.setGeometry(QtCore.QRect(150, 30, 16, 16))
        self.FreeSet_Y_La.setLineWidth(2)
        self.FreeSet_Y_La.setObjectName("FreeSet_Y_La")
        self.FreeSet_X_Box = QtWidgets.QSpinBox(self.Mode_FreeSet_GB)
        self.FreeSet_X_Box.setGeometry(QtCore.QRect(40, 30, 81, 24))
        self.FreeSet_X_Box.setMaximum(320)
        self.FreeSet_X_Box.setObjectName("FreeSet_X_Box")
        self.FreeSet_Y_Box = QtWidgets.QSpinBox(self.Mode_FreeSet_GB)
        self.FreeSet_Y_Box.setGeometry(QtCore.QRect(170, 30, 81, 24))
        self.FreeSet_Y_Box.setMaximum(320)
        self.FreeSet_Y_Box.setObjectName("FreeSet_Y_Box")
        self.Mode_Apply_Bu = QtWidgets.QPushButton(self.Mode_Fr)
        self.Mode_Apply_Bu.setGeometry(QtCore.QRect(12, 340, 291, 32))
        self.Mode_Apply_Bu.setObjectName("Mode_Apply_Bu")
        self.Mode_Circle_Ch = QtWidgets.QRadioButton(self.Mode_Fr)
        self.Mode_Circle_Ch.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.Mode_Circle_Ch.setObjectName("Mode_Circle_Ch")
        self.Mode_Rectangle_Ch = QtWidgets.QRadioButton(self.Mode_Fr)
        self.Mode_Rectangle_Ch.setGeometry(QtCore.QRect(100, 20, 91, 20))
        self.Mode_Rectangle_Ch.setObjectName("Mode_Rectangle_Ch")
        self.Mode_FreeSet_Ch = QtWidgets.QRadioButton(self.Mode_Fr)
        self.Mode_FreeSet_Ch.setGeometry(QtCore.QRect(210, 20, 81, 20))
        self.Mode_FreeSet_Ch.setObjectName("Mode_FreeSet_Ch")
        self.PlateView_Gra = QtWidgets.QGraphicsView(self.centralWidget)
        self.PlateView_Gra.setGeometry(QtCore.QRect(330, 20, 320, 320))
        self.PlateView_Gra.setInteractive(True)
        self.PlateView_Gra.setObjectName("PlateView_Gra")
        self.XAxist_Angle_Gra = QtWidgets.QGraphicsView(self.centralWidget)
        self.XAxist_Angle_Gra.setGeometry(QtCore.QRect(330, 360, 320, 120))
        self.XAxist_Angle_Gra.setObjectName("XAxist_Angle_Gra")
        self.YAxist_Angle_Gra = QtWidgets.QGraphicsView(self.centralWidget)
        self.YAxist_Angle_Gra.setGeometry(QtCore.QRect(330, 500, 320, 120))
        self.YAxist_Angle_Gra.setObjectName("YAxist_Angle_Gra")
        self.PlateView_La = QtWidgets.QLabel(self.centralWidget)
        self.PlateView_La.setGeometry(QtCore.QRect(330, 0, 91, 16))
        self.PlateView_La.setObjectName("PlateView_La")
        self.XAxist_Angle_La = QtWidgets.QLabel(self.centralWidget)
        self.XAxist_Angle_La.setGeometry(QtCore.QRect(330, 340, 91, 16))
        self.XAxist_Angle_La.setObjectName("XAxist_Angle_La")
        self.YAxist_Angle_La = QtWidgets.QLabel(self.centralWidget)
        self.YAxist_Angle_La.setGeometry(QtCore.QRect(330, 480, 91, 16))
        self.YAxist_Angle_La.setObjectName("YAxist_Angle_La")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ball And Plate Control Panel"))
        self.Plate_Controller_La.setText(_translate("MainWindow", "Plate Controller"))
        self.Plate_Controller_Apply_Bu.setText(_translate("MainWindow", "Apply"))
        self.Plate_Controller_PID_GB.setTitle(_translate("MainWindow", "PID Controller"))
        self.PID_Kp_La.setText(_translate("MainWindow", "Kp"))
        self.PID_Kd_La.setText(_translate("MainWindow", "Kd"))
        self.PID_Ki_La.setText(_translate("MainWindow", "Ki"))
        self.Plate_Controller_SMC_GB.setTitle(_translate("MainWindow", "Sliding Mode Control"))
        self.SMC_k1_La.setText(_translate("MainWindow", "k1"))
        self.SMC_K_La.setText(_translate("MainWindow", "K"))
        self.Plate_Controller_PID_Ch.setText(_translate("MainWindow", "PID"))
        self.Plate_Controller_SMC_Ch.setText(_translate("MainWindow", "SMC"))
        self.Mode_La.setText(_translate("MainWindow", "Mode"))
        self.Mode_Circle_GB.setTitle(_translate("MainWindow", "Circle Mode"))
        self.Circle_R_La.setText(_translate("MainWindow", "R"))
        self.Circle_CentralY_La.setText(_translate("MainWindow", "Central Y"))
        self.Circle_CentralX_La.setText(_translate("MainWindow", "Central X"))
        self.Mode_Rectangle_RB.setTitle(_translate("MainWindow", "Rectangle Mode"))
        self.Rectangle_TopLeftX_La.setText(_translate("MainWindow", "Top Left X"))
        self.Rectangle_BotRightX_La.setText(_translate("MainWindow", "Bottom Right X"))
        self.Rectangle_TopLeftY_La.setText(_translate("MainWindow", "Top Left Y"))
        self.Rectangle_BotRightY_La.setText(_translate("MainWindow", "Bottom Right Y"))
        self.Mode_FreeSet_GB.setTitle(_translate("MainWindow", "Free Set Mode"))
        self.FreeSet_X_La.setText(_translate("MainWindow", "X"))
        self.FreeSet_Y_La.setText(_translate("MainWindow", "Y"))
        self.Mode_Apply_Bu.setText(_translate("MainWindow", "Apply"))
        self.Mode_Circle_Ch.setText(_translate("MainWindow", "Circle"))
        self.Mode_Rectangle_Ch.setText(_translate("MainWindow", "Rectangle"))
        self.Mode_FreeSet_Ch.setText(_translate("MainWindow", "Free Set"))
        self.PlateView_La.setText(_translate("MainWindow", "Plate View"))
        self.XAxist_Angle_La.setText(_translate("MainWindow", "X Axist Angle"))
        self.YAxist_Angle_La.setText(_translate("MainWindow", "Y Axist Angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

